//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootcamp20.API.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    using Bootcamp20.DataAccess.Param;

    public partial class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Supplier_id { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Supplier Supplier { get; set; }

        public Item () { }
        public Item (ItemParam itemParam)
        {
            this.Name = itemParam.Name;
            this.Stock = itemParam.Stock;
            this.Price = itemParam.Price;
            this.CreateDate = DateTimeOffset.Now.LocalDateTime;
        }

        public virtual void Update (ItemParam itemParam)
        {
            this.Id = itemParam.Id;
            this.Name = itemParam.Name;
            this.Stock = itemParam.Stock;
            this.Price = itemParam.Price;
            this.UpdateDate = DateTimeOffset.Now.LocalDateTime;
        }

        public virtual void Delete ()
        {
            this.IsDelete = true;
            this.DeleteDate = DateTimeOffset.Now.LocalDateTime;
        }
    }
}
